<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">पूर्ण नाव</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $student->user->name ?? '') }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="email">ईमेल</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email', $student->user->email ?? '') }}" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="password">पासवर्ड {{ isset($student) ? '(बदलायचा असल्यास)' : '' }}</label><input class="form-control @error('password') is-invalid @enderror" id="password" name="password" type="password" @required(! isset($student)) autocomplete="new-password">@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="password_confirmation">पासवर्ड पुन्हा लिहा</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" @required(! isset($student)) autocomplete="new-password"></div>
    <div class="col-md-4"><label class="form-label" for="student_number">विद्यार्थी क्रमांक</label><input class="form-control @error('student_number') is-invalid @enderror" id="student_number" name="student_number" value="{{ old('student_number', $student->student_number ?? '') }}" required>@error('student_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="date_of_birth">जन्मतारीख</label><input class="form-control @error('date_of_birth') is-invalid @enderror" id="date_of_birth" name="date_of_birth" type="date" value="{{ old('date_of_birth', isset($student) ? $student->date_of_birth?->toDateString() : '') }}">@error('date_of_birth')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="gender">लिंग</label><select class="form-select @error('gender') is-invalid @enderror" id="gender" name="gender"><option value="">निवडा</option>@foreach (['female' => 'मुलगी', 'male' => 'मुलगा', 'other' => 'इतर'] as $value => $label)<option value="{{ $value }}" @selected(old('gender', $student->gender ?? '') === $value)>{{ $label }}</option>@endforeach</select>@error('gender')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="joined_on">प्रवेश तारीख</label><input class="form-control @error('joined_on') is-invalid @enderror" id="joined_on" name="joined_on" type="date" value="{{ old('joined_on', isset($student) ? $student->joined_on?->toDateString() : now()->toDateString()) }}" required>@error('joined_on')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="guardian_name">पालकाचे नाव</label><input class="form-control @error('guardian_name') is-invalid @enderror" id="guardian_name" name="guardian_name" value="{{ old('guardian_name', $student->guardian_name ?? '') }}">@error('guardian_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="guardian_phone">पालक फोन</label><input class="form-control @error('guardian_phone') is-invalid @enderror" id="guardian_phone" name="guardian_phone" value="{{ old('guardian_phone', $student->guardian_phone ?? '') }}">@error('guardian_phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    @if (isset($student))
        <div class="col-12"><input name="is_active" type="hidden" value="0"><div class="form-check"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked((bool) old('is_active', $student->user->is_active))><label class="form-check-label" for="is_active">विद्यार्थी खाते सक्रिय आहे</label></div></div>
    @endif
</div>
