<div class="row g-3">
    <div class="col-md-3"><label class="form-label" for="code">Code</label><input class="form-control @error('code') is-invalid @enderror" id="code" name="code" value="{{ old('code', $skill->code) }}" required>@error('code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="name">English name</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $skill->name) }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="name_marathi">मराठी नाव</label><input class="form-control @error('name_marathi') is-invalid @enderror" id="name_marathi" name="name_marathi" value="{{ old('name_marathi', $skill->name_marathi) }}" required>@error('name_marathi')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="parent_skill_id">पूर्व कौशल्य / Parent</label><select class="form-select @error('parent_skill_id') is-invalid @enderror" id="parent_skill_id" name="parent_skill_id"><option value="">मूळ कौशल्य</option>@foreach ($parentSkills as $parentSkill)<option value="{{ $parentSkill->id }}" @selected((string) old('parent_skill_id', $skill->parent_skill_id) === (string) $parentSkill->id)>{{ $parentSkill->name_marathi }} / {{ $parentSkill->name }}</option>@endforeach</select>@error('parent_skill_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-2"><label class="form-label" for="sort_order">क्रम</label><input class="form-control" id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $skill->sort_order) }}" required></div>
    <div class="col-md-8"><label class="form-label" for="description">वर्णन / Description</label><textarea class="form-control" id="description" name="description" rows="2">{{ old('description', $skill->description) }}</textarea></div>
    <div class="col-md-2 d-flex align-items-center"><input name="is_active" type="hidden" value="0"><div class="form-check mt-4"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked((bool) old('is_active', $skill->is_active))><label class="form-check-label" for="is_active">सक्रिय</label></div></div>
</div>
