<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">पूर्ण नाव</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $mentor->user->name ?? '') }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="email">ईमेल</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email', $mentor->user->email ?? '') }}" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="password">पासवर्ड {{ isset($mentor) ? '(बदलायचा असल्यास)' : '' }}</label><input class="form-control @error('password') is-invalid @enderror" id="password" name="password" type="password" @required(! isset($mentor)) autocomplete="new-password">@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="password_confirmation">पासवर्ड पुन्हा लिहा</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" @required(! isset($mentor)) autocomplete="new-password"></div>
    <div class="col-md-4"><label class="form-label" for="employee_number">कर्मचारी क्रमांक</label><input class="form-control @error('employee_number') is-invalid @enderror" id="employee_number" name="employee_number" value="{{ old('employee_number', $mentor->employee_number ?? '') }}">@error('employee_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="phone">फोन</label><input class="form-control @error('phone') is-invalid @enderror" id="phone" name="phone" value="{{ old('phone', $mentor->phone ?? '') }}">@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="qualifications">पात्रता</label><input class="form-control @error('qualifications') is-invalid @enderror" id="qualifications" name="qualifications" value="{{ old('qualifications', $mentor->qualifications ?? '') }}">@error('qualifications')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    @if (isset($mentor))
        <div class="col-12"><input name="is_active" type="hidden" value="0"><div class="form-check"><input class="form-check-input" id="is_active" name="is_active" type="checkbox" value="1" @checked((bool) old('is_active', $mentor->user->is_active))><label class="form-check-label" for="is_active">मार्गदर्शक खाते सक्रिय आहे</label></div></div>
    @endif
</div>
